In [1]:
#Week 2 Homework: Exercises 1-5
#Exercise 1 :Write a function create_board() that creates such a board with the value of each cell set to the integer 0

import random
import numpy as np
def create_board():
    return np.zeros((3,3), dtype=int)
    
board=create_board()

In [2]:
board

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [3]:
#Exercise 2 : write the function place(board, player, position) Players 1 and 2 will take turns changing values of this array from a 0 to a 1 or 2, indicating the number of the player who places a marker there.

#Instructions
#Create a function place(board, player, position), where: player is the current player (an integer 1 or 2).
#position is a tuple of length 2 specifying a desired location to place their marker.
#Your function should only allow the current player to place a marker on the board (change the board position to their number) if that position is empty (zero). Use create_board() to store a board as board, and use place to have Player 1 place a marker on location (0, 0).
def place(board, player, position):
    if board[position] == 0:
        board[position] = player
        return board
    else:
        print("Try again, input not valid")



In [4]:
board = create_board()
place(board, 1, (0, 0))

array([[1, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [5]:
place(board, 1, (0, 0))

Try again, input not valid


In [6]:
#In this exercise 3, we will determine which positions are available to either player for placing their marker
def possibilities(board):
    return [tuple(x) for x in np.argwhere(np.array(board) == 0)]


possibilities(board)


[(0, 1), (0, 2), (1, 0), (1, 1), (1, 2), (2, 0), (2, 1), (2, 2)]

In [7]:
#Exerciese 4 we will select an available board position at random and place a marker there. Write a function random_place(board, player) that places a marker for the current player at random among all the available positions (those currently set to 0). Find possible placements with possibilities(board). Select one possible placement at random using random.choice(selection).
import random
random.seed(1)

def random_place(board, player):
    random_selection = possibilities(board)
    if len(random_selection) > 0:
        random_selection = random.choice(random_selection)
        place(board, player, random_selection)
    return board

random_place(board, 2)

array([[1, 0, 0],
       [2, 0, 0],
       [0, 0, 0]])

In [8]:
# Exercise 5 We will now have both players place three markers each. A new board is given by the sample code. Call random_place(board, player) to place three pieces each on board for players 1 and 2. Print board to see your result.
board = create_board()
for x in range(0,3):
    for player in [1, 2]:
        random_place(board, player)

print(board)

[[1 1 0]
 [0 0 2]
 [2 1 2]]


In [9]:
# Exercise 6  we will make functions that check whether either player has won the game. Check if row win first
def row_win(board, player):
    if np.any(np.all(board==player,axis=1)):
        return True
    else:
        return False

row_win(board, 1)

False

In [10]:
#Exercise 7 Check if coloum win
def col_win(board,player):
    if np.any(np.all(board==player, axis=0)):
        return True
    else:
        return False
col_win(board,1)

False

In [11]:
#Exercise 8 check if diagonal win

def diag_win(board, player):
    diag1 = np.array([board[0,0], board[1,1], board[2,2]])
    diag2 = np.array([board[0,2], board[1,1], board[2,0]])
    if np.all(diag1 == player) or np.all(diag2 == player):
        return True
    else:
        return False
diag_win(board, 2)

False

In [12]:
# Exercise 9 evaluate the board

def evaluate(board):
    winner = 0
    for player in [1, 2]:
        if row_win(board, player):
            winner = player
        elif col_win(board, player):
            winner = player
        elif diag_win(board, player):
            winner = player
    if np.all(board != 0) and winner == 0:
        winner = -1
    return winner

evaluate(board)

0

In [13]:
# Exercises 10 
def play_game():
    board = create_board()
    winner = 0
    while winner == 0:
        for player in [1, 2]:
            random_place(board, player)
            winner = evaluate(board)
            if winner != 0:
                break
    return winner
play_game()
results=[play_game() for i in range(1000)]
results.count(1)

592